Update ubunscanbu-001.yaml

diff --git a/.github/workflows/ubunscanbu-001.yaml b/.github/workflows/ubunscanbu-001.yaml
--- a/.github/workflows/ubunscanbu-001.yaml
+++ b/.github/workflows/ubunscanbu-001.yaml
@@ -41,7 +41,7 @@ jobs:
           export PATH="/usr/lib/llvm-17/bin:$PATH"
           echo "🔍 Checking scan-build installation..."
           which scan-build || { echo "❌ scan-build not found"; exit 1; }
-          scan-build --version || { echo "❌ scan-build version check failed"; exit 1; }
+          # scan-build --version || { echo "❌ scan-build version check failed"; exit 1; }
           echo "✅ scan-build available."
 
       # Clone the DemoIccMAX repository
