Update wasm2.yaml

diff --git a/.github/workflows/wasm2.yaml b/.github/workflows/wasm2.yaml
--- a/.github/workflows/wasm2.yaml
+++ b/.github/workflows/wasm2.yaml
@@ -5,7 +5,7 @@
 ##
 ## Last Updated: 02-AUGUST-2025 at 1400Z by David Hoyt (©)
 #
-## Intent: WASM
+## Intent: WASM2
 #
 ## 
 #
@@ -33,20 +33,26 @@ jobs:
         git config --global user.email "github-actions@github.com"
         git config --global user.name "GitHub Actions"
 
-    - name: Set up Emscripten SDK and Run WASM Build Script
+    - name: Cache Emscripten SDK
+      uses: actions/cache@v4
+      with:
+        path: emsdk
+        key: emsdk-${{ runner.os }}-${{ hashFiles('emsdk/**') }}
+
+    - name: Run WASM Build Script
       run: |
         git clone https://github.com/emscripten-core/emsdk.git
         cd emsdk
         ./emsdk install latest
         ./emsdk activate latest
         source ./emsdk_env.sh
-        bash -c "$(curl -fsSL https://raw.githubusercontent.com/InternationalColorConsortium/DemoIccMAX/refs/heads/wasm/wasm_remote_build.sh)" &> wasm_smoke_test.log
+        bash -c "$(curl -fsSL https://raw.githubusercontent.com/InternationalColorConsortium/DemoIccMAX/refs/heads/wasm/wasm_remote_build.sh)" &> wasm_build.log
 
     - name: Upload WASM Build Logs
       uses: actions/upload-artifact@v4
       with:
-        name: wasm-smoke-test-log
-        path: wasm_smoke_test.log
+        name: wasm-build-log
+        path: wasm_build.log
 
     - name: Gather system information
       run: |
@@ -57,17 +63,26 @@ jobs:
         free -m
         df -h
 
-    - name: Verify Build Success
+    - name: List Build Outputs
       run: |
-        if [ -f DemoIccMAX/Build/CMakeCache.txt ]; then
-          echo "✅ Build configuration successful."
+        ls -R DemoIccMAX/Build
+
+    - name: Verify WASM binaries
+      continue-on-error: true
+      run: |
+        if ls DemoIccMAX/Build/Tools/*.wasm; then
+          echo "✅ WASM binaries exist."
         else
-          echo "❌ Build configuration failed."
-          exit 1
+          echo "⚠️ WASM binaries missing."
         fi
 
-    - name: Upload Build Artifacts
+    - name: Additional Post-Build Debugging
+      run: |
+        find DemoIccMAX/Build/Tools/ -type f \( -name '*.js' -o -name '*.wasm' \) -ls
+        find DemoIccMAX/Build/IccProfLib/ -name '*.a' -exec sh -c 'for obj in $(ar t "$1" | grep "\.o$"); do ar p "$1" "$obj" > "/tmp/$obj"; command -v wasm-objdump && wasm-objdump -x "/tmp/$obj" | head || echo "wasm-objdump not installed"; done' sh {} \;
+
+    - name: Upload WASM Build Artifacts
       uses: actions/upload-artifact@v4
       with:
         name: master-build-linux
-        path: DemoIccMAX/Build/CMakeCache.txt
+        path: DemoIccMAX/Build/Tools/*.wasm
